- name: GitInstall
  hosts: all
  tags: Pre-deployment
  become: yes
  tasks:
   - name: InstallingGIT
     apt:
      update_cache: yes
      name: git
      state: present
   - name: checking All services
     shell: systemctl
     register: GiOut
   - debug:
       var: GiOut.stdout_lines
