- name: GitInstall
  hosts: all
  become: yes
  tasks:
   - name: InstallingGIT
     apt:
      update_cache: yes
      name: git
      state: present
   - name: checking_git_version
     shell: git --version
     register: GitOut
   - debug:
       var: GitOut.stdout_lines
