- name: GitInstall
  hosts: all
  tags: Pre-deployment
  become: yes
  tasks:
   - name: InstallingGIT
     apt:
      update_cache: yes
      name: git
      state: present

 - name: checking_git_version
   hosts: all
   tags: Post-deployment
   shell: git --version
   register: GitOut
 - debug:
      var: GitOut.stdout_lines
