- name: GitInstall
  hosts: all
  tags: Pre-deployment
  become: yes
  vars:
   - tags: Pre-deployment
  tasks:
   - name: InstallingGIT
     apt:
      update_cache: yes
      name: git
      state: present
