- name: GitInstall
  hosts: all
  tags: Pre-deployment
  become: yes
  tasks:
   - name: InstallingGIT
     apt:
      update_cache: yes
      name: git
      state: present

 - name2: Running post verification
   hosts: all
   tags: Post-deployment
   tasks:
    - name: Checcking Installed version
      shell: git --version
      register: GitOut
    - debug:
         var: GitOut.stdout_lines
